FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      ffmpeg \
      python3 \
      python3-pip \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app/

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --default-timeout=120 -r requirements.txt
